# Generated by Django 5.1 on 2024-08-31 05:14

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='uuid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=11, max_length=20, prefix='student_', primary_key=True, serialize=False),
        ),
    ]
